development:
  host: localhost:8080
  email: bt.raines@gmail.com
  password: password
  api_key: 3bbc9e27ccc1d4e77e8f9dafa84d2c535a9d6e6e
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
hosting:
  host: yellow-miller-55.locomotivehosting.com
  api_key: cf916cd3d1a50abea46aff6da2498bdb6c2409a8
  ssl: true
