# Public name of this content type
name: Products

# TODO: explain
slug: products

# Explanation for the backoffice
description: Any menu items (ie. smoothies, juices, specialty items)

# Default field (e.g title)
label_field_name: title

# Order of entries
order_by: manually # default: manually, also available: created_at or any field slug

# Order direction
# order_direction: asc # default: asc, also available: desc

# Display entries grouped by <field> in the backoffice
group_by: type

# Activate public 'create' API (e.g for a contact form)
# public_submission_enabled: false

# Emails to be notified on new entries using the public API
# public_submission_accounts: ['john@acme.net']

# Describe each field. The name shoud always be an underscored string
fields: 
- title: # Name of the field
    label: Title
    type: string
    required: true
    hint: Title of the product (ie. Island Breeze)
    localized: false

- description: # Name of the field
    label: Description
    type: text
    required: false
    hint: Description of the product (ie. Mango, Pineapple, etc.)
    localized: false
    text_formatting: html

- type: # Name of the field
    label: Type
    type: select
    select_options: ['smoothie', 'juice', 'specialty', 'seasonal']
    required: false
    hint: 
    localized: false
